# Generated by Django 5.1.15 on 2026-09-09 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('rtsp_url', models.URLField(max_length=512, verbose_name='RTSP URL')),
                ('location', models.CharField(blank=True, default='', max_length=256, verbose_name='Местоположение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlateDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_text', models.CharField(db_index=True, max_length=20, verbose_name='Текст номера')),
                ('detection_confidence', models.FloatField(verbose_name='Уверенность детекции')),
                ('ocr_confidence', models.FloatField(verbose_name='Уверенность OCR')),
                ('crop_object_key', models.CharField(blank=True, default='', max_length=512, verbose_name='Object key в S3')),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время распознавания')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='detection.camera', verbose_name='Камера')),
            ],
            options={
                'verbose_name': 'Распознанный номер',
                'verbose_name_plural': 'Распознанные номера',
                'ordering': ['-detected_at'],
            },
        ),
    ]
