# Generated by Django 5.1.15 on 2026-09-14 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('rtsp_url', models.URLField(max_length=512, verbose_name='RTSP URL')),
                ('location', models.CharField(blank=True, default='', max_length=256, verbose_name='Местоположение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_text', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Номер')),
                ('status', models.CharField(choices=[('unknown', 'Неизвестен'), ('allowed', 'Разрешён'), ('denied', 'Запрещён')], db_index=True, default='unknown', max_length=10, verbose_name='Статус')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Первое появление')),
                ('last_seen', models.DateTimeField(db_index=True, verbose_name='Последнее появление')),
                ('detection_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во распознаваний')),
                ('last_crop_key', models.CharField(blank=True, default='', max_length=512, verbose_name='Последний кроп (S3)')),
                ('note', models.TextField(blank=True, default='', verbose_name='Заметка')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='PlateDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_confidence', models.FloatField(verbose_name='Уверенность детекции')),
                ('ocr_confidence', models.FloatField(verbose_name='Уверенность OCR')),
                ('crop_object_key', models.CharField(blank=True, default='', max_length=512, verbose_name='Object key в S3')),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время распознавания')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='detection.camera', verbose_name='Камера')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='detection.plate', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Распознавание',
                'verbose_name_plural': 'Распознавания',
                'ordering': ['-detected_at'],
            },
        ),
    ]
