# Generated by Django 5.1.15 on 2026-09-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='photo_key',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Фото номера (S3)'),
        ),
    ]
